### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by coco1254** [mishakorzik/MailFinder#5]
Traceback (most recent call last):                                                                              
  File "MailFinder.py", line 1181, in mailfinder                                                                
  File "/home/kali/.local/lib/python3.10/site-packages/requests/models.py", line 910, in json                   
    return complexjson.loads(self.text, **kwargs)                                                               
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads                              
    return _default_decoder.decode(s)                                                                           
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode                              
    obj, end = self.raw_decode(s)                                                                               
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode                          
    return self.scan_once(s, idx=_w(s, idx).end())                                                              
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                    
                                                                                                                
During handling of the above exception, another exception occurred:                                             
                                                                                                                
Traceback (most recent call last):                                                                              
  File "MailFinder.py", line 1217, in <module>                                                                  
  File "MailFinder.py", line 87, in selecttype                                                                  
  File "MailFinder.py", line 1189, in mailfinder                                                                
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

**Comment by mishakorzik** [comment]
try to install an older version of requests or reinstall
