### ISSUE TITLE
NameError: name 'korzhyk' is not defined

### ISSUE THREAD

**Issue by ghost** [mishakorzik/MailFinder#9]
The program starts fine and seems to work with option 1, when trying option 5 I get this output time and time again: 

Traceback (most recent call last):
  File "MailFinder.py", line 1182, in <module>
  File "MailFinder.py", line 87, in selecttype
  File "MailFinder.py", line 648, in mailfinder
NameError: name 'korzhyk' is not defined

Could you help me find the root cause of this issue?

**Comment by mishakorzik** [comment]
Hi, this is a bug in the tool that i can't fix because there is no good api to validate the email.
